mysql:
  url: ${DATABASE_MYSQL_URL:localhost:3306}
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: adm_videos

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

amqp:
  host: ${AMQP_HOST:localhost}
  port: ${AMQP_PORT:5672}
  username: ${AMQP_USERNAME:admin_videos}
  password: ${AMQP_PASSWORD:123456}