name: CI Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  #job para executar os testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    #config de passos do job
    steps:
      #1. Check source code
      - name: Checkout
        uses: actions/checkout@v3
      #2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      #3. Executar testes da aplicação
      - name: Run tests
        run: ./gradlew test